// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/backupschedule"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// BackupScheduleUpdate is the builder for updating BackupSchedule entities.
type BackupScheduleUpdate struct {
	config
	hooks    []Hook
	mutation *BackupScheduleMutation
}

// Where appends a list predicates to the BackupScheduleUpdate builder.
func (_u *BackupScheduleUpdate) Where(ps ...predicate.BackupSchedule) *BackupScheduleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupScheduleUpdate) SetUpdatedAt(v time.Time) *BackupScheduleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BackupScheduleUpdate) SetGroupID(v uuid.UUID) *BackupScheduleUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BackupScheduleUpdate) SetNillableGroupID(v *uuid.UUID) *BackupScheduleUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BackupScheduleUpdate) SetEnabled(v bool) *BackupScheduleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BackupScheduleUpdate) SetNillableEnabled(v *bool) *BackupScheduleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *BackupScheduleUpdate) SetFrequency(v backupschedule.Frequency) *BackupScheduleUpdate {
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *BackupScheduleUpdate) SetNillableFrequency(v *backupschedule.Frequency) *BackupScheduleUpdate {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// SetTimeOfDay sets the "time_of_day" field.
func (_u *BackupScheduleUpdate) SetTimeOfDay(v string) *BackupScheduleUpdate {
	_u.mutation.SetTimeOfDay(v)
	return _u
}

// SetNillableTimeOfDay sets the "time_of_day" field if the given value is not nil.
func (_u *BackupScheduleUpdate) SetNillableTimeOfDay(v *string) *BackupScheduleUpdate {
	if v != nil {
		_u.SetTimeOfDay(*v)
	}
	return _u
}

// SetRetention sets the "retention" field.
func (_u *BackupScheduleUpdate) SetRetention(v int) *BackupScheduleUpdate {
	_u.mutation.ResetRetention()
	_u.mutation.SetRetention(v)
	return _u
}

// SetNillableRetention sets the "retention" field if the given value is not nil.
func (_u *BackupScheduleUpdate) SetNillableRetention(v *int) *BackupScheduleUpdate {
	if v != nil {
		_u.SetRetention(*v)
	}
	return _u
}

// AddRetention adds value to the "retention" field.
func (_u *BackupScheduleUpdate) AddRetention(v int) *BackupScheduleUpdate {
	_u.mutation.AddRetention(v)
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *BackupScheduleUpdate) SetLastRunAt(v time.Time) *BackupScheduleUpdate {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *BackupScheduleUpdate) SetNillableLastRunAt(v *time.Time) *BackupScheduleUpdate {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *BackupScheduleUpdate) ClearLastRunAt() *BackupScheduleUpdate {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *BackupScheduleUpdate) SetNextRunAt(v time.Time) *BackupScheduleUpdate {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *BackupScheduleUpdate) SetNillableNextRunAt(v *time.Time) *BackupScheduleUpdate {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *BackupScheduleUpdate) ClearNextRunAt() *BackupScheduleUpdate {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BackupScheduleUpdate) SetGroup(v *Group) *BackupScheduleUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the BackupScheduleMutation object of the builder.
func (_u *BackupScheduleUpdate) Mutation() *BackupScheduleMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BackupScheduleUpdate) ClearGroup() *BackupScheduleUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackupScheduleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupScheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackupScheduleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupScheduleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupScheduleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backupschedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupScheduleUpdate) check() error {
	if v, ok := _u.mutation.Frequency(); ok {
		if err := backupschedule.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "BackupSchedule.frequency": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackupSchedule.group"`)
	}
	return nil
}

func (_u *BackupScheduleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupschedule.Table, backupschedule.Columns, sqlgraph.NewFieldSpec(backupschedule.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backupschedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(backupschedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(backupschedule.FieldFrequency, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TimeOfDay(); ok {
		_spec.SetField(backupschedule.FieldTimeOfDay, field.TypeString, value)
	}
	if value, ok := _u.mutation.Retention(); ok {
		_spec.SetField(backupschedule.FieldRetention, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetention(); ok {
		_spec.AddField(backupschedule.FieldRetention, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(backupschedule.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(backupschedule.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(backupschedule.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(backupschedule.FieldNextRunAt, field.TypeTime)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backupschedule.GroupTable,
			Columns: []string{backupschedule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backupschedule.GroupTable,
			Columns: []string{backupschedule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupschedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackupScheduleUpdateOne is the builder for updating a single BackupSchedule entity.
type BackupScheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupScheduleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupScheduleUpdateOne) SetUpdatedAt(v time.Time) *BackupScheduleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *BackupScheduleUpdateOne) SetGroupID(v uuid.UUID) *BackupScheduleUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *BackupScheduleUpdateOne) SetNillableGroupID(v *uuid.UUID) *BackupScheduleUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BackupScheduleUpdateOne) SetEnabled(v bool) *BackupScheduleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BackupScheduleUpdateOne) SetNillableEnabled(v *bool) *BackupScheduleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetFrequency sets the "frequency" field.
func (_u *BackupScheduleUpdateOne) SetFrequency(v backupschedule.Frequency) *BackupScheduleUpdateOne {
	_u.mutation.SetFrequency(v)
	return _u
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_u *BackupScheduleUpdateOne) SetNillableFrequency(v *backupschedule.Frequency) *BackupScheduleUpdateOne {
	if v != nil {
		_u.SetFrequency(*v)
	}
	return _u
}

// SetTimeOfDay sets the "time_of_day" field.
func (_u *BackupScheduleUpdateOne) SetTimeOfDay(v string) *BackupScheduleUpdateOne {
	_u.mutation.SetTimeOfDay(v)
	return _u
}

// SetNillableTimeOfDay sets the "time_of_day" field if the given value is not nil.
func (_u *BackupScheduleUpdateOne) SetNillableTimeOfDay(v *string) *BackupScheduleUpdateOne {
	if v != nil {
		_u.SetTimeOfDay(*v)
	}
	return _u
}

// SetRetention sets the "retention" field.
func (_u *BackupScheduleUpdateOne) SetRetention(v int) *BackupScheduleUpdateOne {
	_u.mutation.ResetRetention()
	_u.mutation.SetRetention(v)
	return _u
}

// SetNillableRetention sets the "retention" field if the given value is not nil.
func (_u *BackupScheduleUpdateOne) SetNillableRetention(v *int) *BackupScheduleUpdateOne {
	if v != nil {
		_u.SetRetention(*v)
	}
	return _u
}

// AddRetention adds value to the "retention" field.
func (_u *BackupScheduleUpdateOne) AddRetention(v int) *BackupScheduleUpdateOne {
	_u.mutation.AddRetention(v)
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *BackupScheduleUpdateOne) SetLastRunAt(v time.Time) *BackupScheduleUpdateOne {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *BackupScheduleUpdateOne) SetNillableLastRunAt(v *time.Time) *BackupScheduleUpdateOne {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *BackupScheduleUpdateOne) ClearLastRunAt() *BackupScheduleUpdateOne {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *BackupScheduleUpdateOne) SetNextRunAt(v time.Time) *BackupScheduleUpdateOne {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *BackupScheduleUpdateOne) SetNillableNextRunAt(v *time.Time) *BackupScheduleUpdateOne {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *BackupScheduleUpdateOne) ClearNextRunAt() *BackupScheduleUpdateOne {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *BackupScheduleUpdateOne) SetGroup(v *Group) *BackupScheduleUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the BackupScheduleMutation object of the builder.
func (_u *BackupScheduleUpdateOne) Mutation() *BackupScheduleMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *BackupScheduleUpdateOne) ClearGroup() *BackupScheduleUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the BackupScheduleUpdate builder.
func (_u *BackupScheduleUpdateOne) Where(ps ...predicate.BackupSchedule) *BackupScheduleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackupScheduleUpdateOne) Select(field string, fields ...string) *BackupScheduleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BackupSchedule entity.
func (_u *BackupScheduleUpdateOne) Save(ctx context.Context) (*BackupSchedule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupScheduleUpdateOne) SaveX(ctx context.Context) *BackupSchedule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackupScheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupScheduleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupScheduleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backupschedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupScheduleUpdateOne) check() error {
	if v, ok := _u.mutation.Frequency(); ok {
		if err := backupschedule.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "BackupSchedule.frequency": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackupSchedule.group"`)
	}
	return nil
}

func (_u *BackupScheduleUpdateOne) sqlSave(ctx context.Context) (_node *BackupSchedule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupschedule.Table, backupschedule.Columns, sqlgraph.NewFieldSpec(backupschedule.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackupSchedule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backupschedule.FieldID)
		for _, f := range fields {
			if !backupschedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backupschedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backupschedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(backupschedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Frequency(); ok {
		_spec.SetField(backupschedule.FieldFrequency, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TimeOfDay(); ok {
		_spec.SetField(backupschedule.FieldTimeOfDay, field.TypeString, value)
	}
	if value, ok := _u.mutation.Retention(); ok {
		_spec.SetField(backupschedule.FieldRetention, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetention(); ok {
		_spec.AddField(backupschedule.FieldRetention, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(backupschedule.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(backupschedule.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(backupschedule.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(backupschedule.FieldNextRunAt, field.TypeTime)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backupschedule.GroupTable,
			Columns: []string{backupschedule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backupschedule.GroupTable,
			Columns: []string{backupschedule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BackupSchedule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupschedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
