// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/backupschedule"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// BackupSchedule is the model entity for the BackupSchedule schema.
type BackupSchedule struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uuid.UUID `json:"group_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Frequency holds the value of the "frequency" field.
	Frequency backupschedule.Frequency `json:"frequency,omitempty"`
	// TimeOfDay holds the value of the "time_of_day" field.
	TimeOfDay string `json:"time_of_day,omitempty"`
	// Retention holds the value of the "retention" field.
	Retention int `json:"retention,omitempty"`
	// LastRunAt holds the value of the "last_run_at" field.
	LastRunAt *time.Time `json:"last_run_at,omitempty"`
	// NextRunAt holds the value of the "next_run_at" field.
	NextRunAt *time.Time `json:"next_run_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BackupScheduleQuery when eager-loading is set.
	Edges        BackupScheduleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BackupScheduleEdges holds the relations/edges for other nodes in the graph.
type BackupScheduleEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BackupScheduleEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BackupSchedule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backupschedule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case backupschedule.FieldRetention:
			values[i] = new(sql.NullInt64)
		case backupschedule.FieldFrequency, backupschedule.FieldTimeOfDay:
			values[i] = new(sql.NullString)
		case backupschedule.FieldCreatedAt, backupschedule.FieldUpdatedAt, backupschedule.FieldLastRunAt, backupschedule.FieldNextRunAt:
			values[i] = new(sql.NullTime)
		case backupschedule.FieldID, backupschedule.FieldGroupID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BackupSchedule fields.
func (_m *BackupSchedule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backupschedule.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case backupschedule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case backupschedule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case backupschedule.FieldGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value != nil {
				_m.GroupID = *value
			}
		case backupschedule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case backupschedule.FieldFrequency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field frequency", values[i])
			} else if value.Valid {
				_m.Frequency = backupschedule.Frequency(value.String)
			}
		case backupschedule.FieldTimeOfDay:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field time_of_day", values[i])
			} else if value.Valid {
				_m.TimeOfDay = value.String
			}
		case backupschedule.FieldRetention:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retention", values[i])
			} else if value.Valid {
				_m.Retention = int(value.Int64)
			}
		case backupschedule.FieldLastRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_at", values[i])
			} else if value.Valid {
				_m.LastRunAt = new(time.Time)
				*_m.LastRunAt = value.Time
			}
		case backupschedule.FieldNextRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_run_at", values[i])
			} else if value.Valid {
				_m.NextRunAt = new(time.Time)
				*_m.NextRunAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BackupSchedule.
// This includes values selected through modifiers, order, etc.
func (_m *BackupSchedule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the BackupSchedule entity.
func (_m *BackupSchedule) QueryGroup() *GroupQuery {
	return NewBackupScheduleClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this BackupSchedule.
// Note that you need to call BackupSchedule.Unwrap() before calling this method if this BackupSchedule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BackupSchedule) Update() *BackupScheduleUpdateOne {
	return NewBackupScheduleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BackupSchedule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BackupSchedule) Unwrap() *BackupSchedule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BackupSchedule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BackupSchedule) String() string {
	var builder strings.Builder
	builder.WriteString("BackupSchedule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("frequency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Frequency))
	builder.WriteString(", ")
	builder.WriteString("time_of_day=")
	builder.WriteString(_m.TimeOfDay)
	builder.WriteString(", ")
	builder.WriteString("retention=")
	builder.WriteString(fmt.Sprintf("%v", _m.Retention))
	builder.WriteString(", ")
	if v := _m.LastRunAt; v != nil {
		builder.WriteString("last_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextRunAt; v != nil {
		builder.WriteString("next_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BackupSchedules is a parsable slice of BackupSchedule.
type BackupSchedules []*BackupSchedule
