// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/backupschedule"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// BackupScheduleCreate is the builder for creating a BackupSchedule entity.
type BackupScheduleCreate struct {
	config
	mutation *BackupScheduleMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *BackupScheduleCreate) SetCreatedAt(v time.Time) *BackupScheduleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableCreatedAt(v *time.Time) *BackupScheduleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BackupScheduleCreate) SetUpdatedAt(v time.Time) *BackupScheduleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableUpdatedAt(v *time.Time) *BackupScheduleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *BackupScheduleCreate) SetGroupID(v uuid.UUID) *BackupScheduleCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *BackupScheduleCreate) SetEnabled(v bool) *BackupScheduleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableEnabled(v *bool) *BackupScheduleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetFrequency sets the "frequency" field.
func (_c *BackupScheduleCreate) SetFrequency(v backupschedule.Frequency) *BackupScheduleCreate {
	_c.mutation.SetFrequency(v)
	return _c
}

// SetNillableFrequency sets the "frequency" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableFrequency(v *backupschedule.Frequency) *BackupScheduleCreate {
	if v != nil {
		_c.SetFrequency(*v)
	}
	return _c
}

// SetTimeOfDay sets the "time_of_day" field.
func (_c *BackupScheduleCreate) SetTimeOfDay(v string) *BackupScheduleCreate {
	_c.mutation.SetTimeOfDay(v)
	return _c
}

// SetNillableTimeOfDay sets the "time_of_day" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableTimeOfDay(v *string) *BackupScheduleCreate {
	if v != nil {
		_c.SetTimeOfDay(*v)
	}
	return _c
}

// SetRetention sets the "retention" field.
func (_c *BackupScheduleCreate) SetRetention(v int) *BackupScheduleCreate {
	_c.mutation.SetRetention(v)
	return _c
}

// SetNillableRetention sets the "retention" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableRetention(v *int) *BackupScheduleCreate {
	if v != nil {
		_c.SetRetention(*v)
	}
	return _c
}

// SetLastRunAt sets the "last_run_at" field.
func (_c *BackupScheduleCreate) SetLastRunAt(v time.Time) *BackupScheduleCreate {
	_c.mutation.SetLastRunAt(v)
	return _c
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableLastRunAt(v *time.Time) *BackupScheduleCreate {
	if v != nil {
		_c.SetLastRunAt(*v)
	}
	return _c
}

// SetNextRunAt sets the "next_run_at" field.
func (_c *BackupScheduleCreate) SetNextRunAt(v time.Time) *BackupScheduleCreate {
	_c.mutation.SetNextRunAt(v)
	return _c
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableNextRunAt(v *time.Time) *BackupScheduleCreate {
	if v != nil {
		_c.SetNextRunAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BackupScheduleCreate) SetID(v uuid.UUID) *BackupScheduleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BackupScheduleCreate) SetNillableID(v *uuid.UUID) *BackupScheduleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *BackupScheduleCreate) SetGroup(v *Group) *BackupScheduleCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the BackupScheduleMutation object of the builder.
func (_c *BackupScheduleCreate) Mutation() *BackupScheduleMutation {
	return _c.mutation
}

// Save creates the BackupSchedule in the database.
func (_c *BackupScheduleCreate) Save(ctx context.Context) (*BackupSchedule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BackupScheduleCreate) SaveX(ctx context.Context) *BackupSchedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackupScheduleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackupScheduleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BackupScheduleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := backupschedule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := backupschedule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := backupschedule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Frequency(); !ok {
		v := backupschedule.DefaultFrequency
		_c.mutation.SetFrequency(v)
	}
	if _, ok := _c.mutation.TimeOfDay(); !ok {
		v := backupschedule.DefaultTimeOfDay
		_c.mutation.SetTimeOfDay(v)
	}
	if _, ok := _c.mutation.Retention(); !ok {
		v := backupschedule.DefaultRetention
		_c.mutation.SetRetention(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := backupschedule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BackupScheduleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BackupSchedule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BackupSchedule.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "BackupSchedule.group_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "BackupSchedule.enabled"`)}
	}
	if _, ok := _c.mutation.Frequency(); !ok {
		return &ValidationError{Name: "frequency", err: errors.New(`ent: missing required field "BackupSchedule.frequency"`)}
	}
	if v, ok := _c.mutation.Frequency(); ok {
		if err := backupschedule.FrequencyValidator(v); err != nil {
			return &ValidationError{Name: "frequency", err: fmt.Errorf(`ent: validator failed for field "BackupSchedule.frequency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TimeOfDay(); !ok {
		return &ValidationError{Name: "time_of_day", err: errors.New(`ent: missing required field "BackupSchedule.time_of_day"`)}
	}
	if _, ok := _c.mutation.Retention(); !ok {
		return &ValidationError{Name: "retention", err: errors.New(`ent: missing required field "BackupSchedule.retention"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "BackupSchedule.group"`)}
	}
	return nil
}

func (_c *BackupScheduleCreate) sqlSave(ctx context.Context) (*BackupSchedule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BackupScheduleCreate) createSpec() (*BackupSchedule, *sqlgraph.CreateSpec) {
	var (
		_node = &BackupSchedule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(backupschedule.Table, sqlgraph.NewFieldSpec(backupschedule.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(backupschedule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(backupschedule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(backupschedule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Frequency(); ok {
		_spec.SetField(backupschedule.FieldFrequency, field.TypeEnum, value)
		_node.Frequency = value
	}
	if value, ok := _c.mutation.TimeOfDay(); ok {
		_spec.SetField(backupschedule.FieldTimeOfDay, field.TypeString, value)
		_node.TimeOfDay = value
	}
	if value, ok := _c.mutation.Retention(); ok {
		_spec.SetField(backupschedule.FieldRetention, field.TypeInt, value)
		_node.Retention = value
	}
	if value, ok := _c.mutation.LastRunAt(); ok {
		_spec.SetField(backupschedule.FieldLastRunAt, field.TypeTime, value)
		_node.LastRunAt = &value
	}
	if value, ok := _c.mutation.NextRunAt(); ok {
		_spec.SetField(backupschedule.FieldNextRunAt, field.TypeTime, value)
		_node.NextRunAt = &value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backupschedule.GroupTable,
			Columns: []string{backupschedule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BackupScheduleCreateBulk is the builder for creating many BackupSchedule entities in bulk.
type BackupScheduleCreateBulk struct {
	config
	err      error
	builders []*BackupScheduleCreate
}

// Save creates the BackupSchedule entities in the database.
func (_c *BackupScheduleCreateBulk) Save(ctx context.Context) ([]*BackupSchedule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BackupSchedule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BackupScheduleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BackupScheduleCreateBulk) SaveX(ctx context.Context) []*BackupSchedule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackupScheduleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackupScheduleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
