// Code generated by ent, DO NOT EDIT.

package backupschedule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldGroupID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldEnabled, v))
}

// TimeOfDay applies equality check predicate on the "time_of_day" field. It's identical to TimeOfDayEQ.
func TimeOfDay(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldTimeOfDay, v))
}

// Retention applies equality check predicate on the "retention" field. It's identical to RetentionEQ.
func Retention(v int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldRetention, v))
}

// LastRunAt applies equality check predicate on the "last_run_at" field. It's identical to LastRunAtEQ.
func LastRunAt(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldLastRunAt, v))
}

// NextRunAt applies equality check predicate on the "next_run_at" field. It's identical to NextRunAtEQ.
func NextRunAt(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldNextRunAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLTE(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...uuid.UUID) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldGroupID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldEnabled, v))
}

// FrequencyEQ applies the EQ predicate on the "frequency" field.
func FrequencyEQ(v Frequency) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldFrequency, v))
}

// FrequencyNEQ applies the NEQ predicate on the "frequency" field.
func FrequencyNEQ(v Frequency) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldFrequency, v))
}

// FrequencyIn applies the In predicate on the "frequency" field.
func FrequencyIn(vs ...Frequency) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldFrequency, vs...))
}

// FrequencyNotIn applies the NotIn predicate on the "frequency" field.
func FrequencyNotIn(vs ...Frequency) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldFrequency, vs...))
}

// TimeOfDayEQ applies the EQ predicate on the "time_of_day" field.
func TimeOfDayEQ(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldTimeOfDay, v))
}

// TimeOfDayNEQ applies the NEQ predicate on the "time_of_day" field.
func TimeOfDayNEQ(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldTimeOfDay, v))
}

// TimeOfDayIn applies the In predicate on the "time_of_day" field.
func TimeOfDayIn(vs ...string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldTimeOfDay, vs...))
}

// TimeOfDayNotIn applies the NotIn predicate on the "time_of_day" field.
func TimeOfDayNotIn(vs ...string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldTimeOfDay, vs...))
}

// TimeOfDayGT applies the GT predicate on the "time_of_day" field.
func TimeOfDayGT(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGT(FieldTimeOfDay, v))
}

// TimeOfDayGTE applies the GTE predicate on the "time_of_day" field.
func TimeOfDayGTE(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGTE(FieldTimeOfDay, v))
}

// TimeOfDayLT applies the LT predicate on the "time_of_day" field.
func TimeOfDayLT(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLT(FieldTimeOfDay, v))
}

// TimeOfDayLTE applies the LTE predicate on the "time_of_day" field.
func TimeOfDayLTE(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLTE(FieldTimeOfDay, v))
}

// TimeOfDayContains applies the Contains predicate on the "time_of_day" field.
func TimeOfDayContains(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldContains(FieldTimeOfDay, v))
}

// TimeOfDayHasPrefix applies the HasPrefix predicate on the "time_of_day" field.
func TimeOfDayHasPrefix(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldHasPrefix(FieldTimeOfDay, v))
}

// TimeOfDayHasSuffix applies the HasSuffix predicate on the "time_of_day" field.
func TimeOfDayHasSuffix(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldHasSuffix(FieldTimeOfDay, v))
}

// TimeOfDayEqualFold applies the EqualFold predicate on the "time_of_day" field.
func TimeOfDayEqualFold(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEqualFold(FieldTimeOfDay, v))
}

// TimeOfDayContainsFold applies the ContainsFold predicate on the "time_of_day" field.
func TimeOfDayContainsFold(v string) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldContainsFold(FieldTimeOfDay, v))
}

// RetentionEQ applies the EQ predicate on the "retention" field.
func RetentionEQ(v int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldRetention, v))
}

// RetentionNEQ applies the NEQ predicate on the "retention" field.
func RetentionNEQ(v int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldRetention, v))
}

// RetentionIn applies the In predicate on the "retention" field.
func RetentionIn(vs ...int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldRetention, vs...))
}

// RetentionNotIn applies the NotIn predicate on the "retention" field.
func RetentionNotIn(vs ...int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldRetention, vs...))
}

// RetentionGT applies the GT predicate on the "retention" field.
func RetentionGT(v int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGT(FieldRetention, v))
}

// RetentionGTE applies the GTE predicate on the "retention" field.
func RetentionGTE(v int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGTE(FieldRetention, v))
}

// RetentionLT applies the LT predicate on the "retention" field.
func RetentionLT(v int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLT(FieldRetention, v))
}

// RetentionLTE applies the LTE predicate on the "retention" field.
func RetentionLTE(v int) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLTE(FieldRetention, v))
}

// LastRunAtEQ applies the EQ predicate on the "last_run_at" field.
func LastRunAtEQ(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldLastRunAt, v))
}

// LastRunAtNEQ applies the NEQ predicate on the "last_run_at" field.
func LastRunAtNEQ(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldLastRunAt, v))
}

// LastRunAtIn applies the In predicate on the "last_run_at" field.
func LastRunAtIn(vs ...time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldLastRunAt, vs...))
}

// LastRunAtNotIn applies the NotIn predicate on the "last_run_at" field.
func LastRunAtNotIn(vs ...time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldLastRunAt, vs...))
}

// LastRunAtGT applies the GT predicate on the "last_run_at" field.
func LastRunAtGT(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGT(FieldLastRunAt, v))
}

// LastRunAtGTE applies the GTE predicate on the "last_run_at" field.
func LastRunAtGTE(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGTE(FieldLastRunAt, v))
}

// LastRunAtLT applies the LT predicate on the "last_run_at" field.
func LastRunAtLT(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLT(FieldLastRunAt, v))
}

// LastRunAtLTE applies the LTE predicate on the "last_run_at" field.
func LastRunAtLTE(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLTE(FieldLastRunAt, v))
}

// LastRunAtIsNil applies the IsNil predicate on the "last_run_at" field.
func LastRunAtIsNil() predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIsNull(FieldLastRunAt))
}

// LastRunAtNotNil applies the NotNil predicate on the "last_run_at" field.
func LastRunAtNotNil() predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotNull(FieldLastRunAt))
}

// NextRunAtEQ applies the EQ predicate on the "next_run_at" field.
func NextRunAtEQ(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldEQ(FieldNextRunAt, v))
}

// NextRunAtNEQ applies the NEQ predicate on the "next_run_at" field.
func NextRunAtNEQ(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNEQ(FieldNextRunAt, v))
}

// NextRunAtIn applies the In predicate on the "next_run_at" field.
func NextRunAtIn(vs ...time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIn(FieldNextRunAt, vs...))
}

// NextRunAtNotIn applies the NotIn predicate on the "next_run_at" field.
func NextRunAtNotIn(vs ...time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotIn(FieldNextRunAt, vs...))
}

// NextRunAtGT applies the GT predicate on the "next_run_at" field.
func NextRunAtGT(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGT(FieldNextRunAt, v))
}

// NextRunAtGTE applies the GTE predicate on the "next_run_at" field.
func NextRunAtGTE(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldGTE(FieldNextRunAt, v))
}

// NextRunAtLT applies the LT predicate on the "next_run_at" field.
func NextRunAtLT(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLT(FieldNextRunAt, v))
}

// NextRunAtLTE applies the LTE predicate on the "next_run_at" field.
func NextRunAtLTE(v time.Time) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldLTE(FieldNextRunAt, v))
}

// NextRunAtIsNil applies the IsNil predicate on the "next_run_at" field.
func NextRunAtIsNil() predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldIsNull(FieldNextRunAt))
}

// NextRunAtNotNil applies the NotNil predicate on the "next_run_at" field.
func NextRunAtNotNil() predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.FieldNotNull(FieldNextRunAt))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.BackupSchedule {
	return predicate.BackupSchedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.BackupSchedule {
	return predicate.BackupSchedule(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BackupSchedule) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BackupSchedule) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BackupSchedule) predicate.BackupSchedule {
	return predicate.BackupSchedule(sql.NotPredicates(p))
}
